@startuml
!include style.puml
skinparam arrowThickness 1.1
skinparam arrowColor LOGIC_COLOR_T4
skinparam classBackgroundColor LOGIC_COLOR

package Logic {

Class CommandResult
Class AddressBookParser
Interface Command <<Interface>>
Interface ApplicationState <<Interface>>

Interface Logic <<Interface>>
Class LogicManager
}

package Model{
Class HiddenModel #FFFFFF
}

package Storage{
}

Class HiddenOutside #FFFFFF
HiddenOutside ..> Logic

LogicManager .right.|> Logic
LogicManager -right->"1" AddressBookParser
LogicManager --> "currentApplicationState 1" ApplicationState

AddressBookParser ..> Command : creates >
AddressBookParser ..> ApplicationState

Command ..> ApplicationState : checks >
LogicManager ..> Command : executes >

LogicManager --> Model
LogicManager --> Storage
Storage --[hidden] Model
Command .[hidden]up.> Storage
Command .right.> Model : modifies >

Logic ..> CommandResult
LogicManager .left.> CommandResult
Command .up.> CommandResult : produces >

CommandResult --> "1 nextApplicationState" ApplicationState
@enduml
