@startuml
'https://plantuml.com/activity-diagram-beta

start

:User executes ""mark as done"" command;
:LogicManager takes in the user input;
:AddressBookParser parses the user input with the current app state;


if () then ([input format is valid])
    :Task index is retrieved from
    the user input and the group specified
    by the current app state;

    :LogicManager checks if the command is
    able to run in the current app state;

    if () then ([command can be run in current app state])

    :Check if task index is valid;

    if () then ([task index is valid])
    :Check if task is already marked as ""done"";

    if () then ([task is not done])
        :Mark task as ""done"";

    else ([else])
    :Show error message
    indicating task already
    marked as done;

    endif

    else ([else])
    :Show error message indicating
    invalid task index;

    endif

    else ([else])
    :Show error message indicating
    command cannot be run in
    current app state;

    endif

else ([else])
    :Show error message indicating
    invalid input format;

endif

stop

@enduml
