@startuml
'https://plantuml.com/activity-diagram-beta

start

:User executes ""mark as done"" command;
:LogicManager takes in the user input;
:AddressBookParser parses the user input with the current app state;


if () then ([input format is valid])
    :MarkAsDoneCommandParser retrieves
    task index from the user input
    and the group specified by the
    current app state;

    :LogicManager checks if the command is
    able to run in the current app state;

    if () then ([command can be run in current app state])

    :MarkAsDoneCommand checks
    if task index is valid;

    if () then ([task index is valid])
    :MarkAsDoneCommand checks
    if task is already marked as ""done"";

    if () then ([task is not done])
        :Marks task as ""done"";

    else ([else])
    :Throws CommandException;
    :Ui catches CommandException;

    endif

    else ([else])
    :Throws CommandException;
        :Ui catches CommandException;

    endif

    else ([else])
    :Throws CommandException;
    :Ui catches CommandException;

    endif

else ([else])
    :Throws ParseException;
    :Ui catches ParseException;

endif
:UI displays the result to the User;

stop

@enduml
